apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1        # Версия API для работы с объектами Deployment. "apps/v1" — это стабильная версия, предназначенная для управления приложениями.
    kind: Deployment           # Тип объекта, указывающий, что это Deployment — объект, управляющий развертыванием и обновлением подов.
    metadata: # Метаданные для объекта, включающие имя и метки.
      name: kubertest-deployment # Имя Deployment — "kubertest-deployment", которое используется для ссылки на этот объект.
      labels: # Метки, которые могут быть использованы для поиска и организации объектов.
        app: kubertest         # Метка, которая может быть использована для выбора этого Deployment в дальнейшем (например, для сервисов или подов).
    spec: # Спецификация Deployment.
      replicas: 1              # Количество реплик подов, которые должны быть запущены (в данном случае 1 под).
      selector: # Селектор для выбора подов, управляемых этим Deployment.
        matchLabels: # Подбор подов по меткам.
          app: kubertest       # Этот Deployment управляет подами с меткой app=kubertest.
      template: # Шаблон для создания подов, которые будут запускаться.
        metadata: # Метаданные для шаблона пода.
          labels:
            app: kubertest     # Метка app=kubertest для всех подов, создаваемых этим Deployment.
        spec: # Спецификация контейнеров внутри подов.
          containers: # Список контейнеров, которые будут работать в поде.
            - name: kubertest  # Имя контейнера — "kubertest".
              image: kubertest:latest  # Docker-образ для контейнера. Указан образ с Docker Hub.
              imagePullPolicy: IfNotPresent  # Политика загрузки образа. "IfNotPresent" означает, что образ будет загружен, только если его нет локально.
              ports: # Порты, которые контейнер будет слушать.
                - name: http     # Имя порта — "http".
                  containerPort: 8089  # Порт, который контейнер будет использовать внутри пода (8089).
              resources: # Ограничения ресурсов для контейнера.
                limits:
                  memory: "200Mi"  # Ограничение на память контейнера — 200 МБ.
              envFrom:
                - configMapRef:
                    name: kubertest-config
          volumes:
            - name: kunertest-config
              configMap:
                name: kubertest-config
  - apiVersion: v1              # Версия API для работы с сервисами в Kubernetes. "v1" — стабильная версия.
    kind: Service               # Тип объекта — Service (сервис), который абстрагирует доступ к набору подов.
    metadata: # Метаданные для объекта, включая имя и метки.
      name: kubertest-service   # Имя сервиса — "kubertest".
      labels: # Метки для объектaа.
        app: kubertest          # Метка, которая может быть использована для выбора этого сервиса.
    spec: # Спецификация сервиса.
      type: LoadBalancer        # Тип сервиса — "LoadBalancer", который создаст балансировщик нагрузки для доступа к сервису извне (подходит для облачных платформ).
      selector: # Селектор, который указывает, какие поды должны быть обслужены этим сервисом.
        app: kubertest          # Сервис будет направлять трафик к подам с меткой app=kubertest.
      ports: # Порты, которые будут использоваться для доступа к сервису.
        - protocol: TCP         # Протокол, который будет использоваться для связи — TCP.
          name: http            # Имя порта — "http".
          port: 8089            # Порт, на котором сервис будет слушать запросы (порт 8089).
          targetPort: 8089      # Порт, на который сервис будет перенаправлять трафик в контейнерах (также 8089).