apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: kubertest
data:
  POSTGRES_DB: "test"            # Имя базы данных
  POSTGRES_USER: "postgres"      # Имя пользователя базы данных
  POSTGRES_PASSWORD: "sa"        # Пароль пользователя базы данных
  POSTGRES_PORT: "5432"          # Порт базы данных